### ISSUE TITLE
数据路径找不到以及data文件夹层级关系

### ISSUE THREAD

**Issue by yijieZengz** [XiaohanLei/IEVE#4]
作者您好，非常感谢您杰出的工作，该工作我受益匪浅，于是我尝试复现该工作，但是遇见以下问题，如果您有时间，能否帮忙解答一下我的疑问？
问题1>我在执行python main.py时，出现上述以下报错：
Traceback (most recent call last):
  File "/mnt/disk2/zyj/user_zyj/habitatIEVE/IEVE/main.py", line 766, in <module>
    main()
  File "/mnt/disk2/zyj/user_zyj/habitatIEVE/IEVE/main.py", line 102, in main
    envs = make_vec_envs(args)
  File "/mnt/disk2/zyj/user_zyj/habitatIEVE/IEVE/envs/__init__.py", line 7, in make_vec_envs
    envs = construct_envs(args)
  File "/mnt/disk2/zyj/user_zyj/habitatIEVE/IEVE/envs/habitat/__init__.py", line 69, in construct_envs
    scenes = dataset.get_scenes_to_load(basic_config.habitat.dataset)
  File "/mnt/disk2/zyj/user_zyj/habitatIEVE/IEVE/3rdparty/habitat-lab-0.2.3/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 51, in get_scenes_to_load
    raise FileNotFoundError(
FileNotFoundError: Could not find dataset file `data/datasets/instance_imagenav/hm3d/v3/val`
。但是实际上在是存在IEVE/data/datasets/instance_imagenav/hm3d/v3/val路径下是存在这样的路径的。请问这个路径下放的是任务数据集么？
问题2>:作者您是否方便详细展示一下data文件夹的层级关系，这样我在复现的时候能清楚的知道下载那些数据文件以及如何安排这些文件的路径。
感谢您在百忙之中抽空回复！这对我非常重要。

**Comment by XiaohanLei** [comment]
![image](https://github.com/user-attachments/assets/4688dd15-fea6-4841-a3c2-3e5904be08ce)
for the quesion 1,
yes, in the 'datasets' sub dir, they are 'episode' datasets, while in the 'scene_datasets'
, they are scene datasets
for the question 2,
I have attatched a screen cut from my data dir

**Comment by yijieZengz** [comment]
Thank you very much for your timely reply, which is very useful to me. Next, I will try to repeat the reform work according to your answer, and we will ask you again if there are any questions in the future. Thank you again for your outstanding work and prompt response.
